name: ObscuraX.Shared

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ObscuraX.Shared.yaml'
      - 'src/ObscuraX.Shared/**'
      - 'src/props/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/ObscuraX.Shared.yaml'
      - 'src/ObscuraX.Shared/**'
      - 'src/props/**'

jobs:
  build:
    name: "ObscuraX.Shared Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v5
      name: Setup .NET
      with:
        dotnet-version: 9.x
        
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: src/ObscuraX.Shared
        github_token: ${{ secrets.PAT }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
